version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development

    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
