version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_USER=root
      - MONGO_PASSWORD=root
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
